<a href="https://colab.research.google.com/github/SovetovAleksey/Linear-algebra/blob/4_quest/4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import numpy.linalg
import scipy.linalg

# Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Система имеее количество уравнений меньшее, чем количество неизвестных ⇒  система является недоопределённой

Запишем матрицу системы

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 &-2\\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Приведем к ступенчатому виду, вычтем из 3 строки первую

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 &-2\\ 
2 & 1 & -1 & 1 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из 2 строки первую, умноженную на 2

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 &-2\\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Прибавим вторую строку к первой:

\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
-2\\ 
-2\\
4
\end{matrix}
\end{pmatrix}

Ранг матрицы системы уравнений и ранг расширенной матрицы равны, $rankA = rankà = 3$, система имеет множество решений

Пусть $x_4 = c$, тогда

$-2x_{3}+3c=4\\x_3=-\frac{4-3c}{2}\\x_{3}=-2+\frac{3}{2}c\\-x_{2}+x_{3}+5c=-2\\x_2=2+5c-2+\frac{3}{2}c\\x_2=\frac{13}{2}c\\ x_{1}+3c=-2\\x_1=-2-3c$

Общее решение системы уравнений

$x_1=-2-3c$

$x_2=\frac{13}{2}c$

$x_3=-2+\frac{3}{2}c$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


$a) \begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Найдем ранги матрицы системы и ранг расширенной матрицы ⇒ $rankA = rankà = 3 ⇒$ поскольку ранги равны, система имеет одно единственное решение

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Сразу видно, что вектора линейно зависимы (1 строка равна второй, умноженной на 2, 3 строка равна второй, умноженной на 3), а вектор коэфициентов $\bar{b}=\begin{pmatrix}1\\-2\\5\end{pmatrix}$ не принадлежит линейному подпространству образованному ими, следовательно, система решений не имеет

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}

Поскольку $rankA = rankÃ$, но количество уравнений меньше количества неизвестных ⇒ система совместна, но неопределена, и имеет множество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Найдем ранги матрицы системы и ранг расширенной матрицы ⇒ $rankA = rankà = 4 ⇒$ поскольку ранги равны, система имеет одно единственное решение

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Вычтем из 2 строки первую, умноженную на 2, и из 3 строки первую, умноженную на 2

\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}

Вычтем из 3 строки вторую, умноженную на 2

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c+a-2b
\end{matrix}
\end{pmatrix}$$

Поменяем метсами 1 и 3 столбец

$$\begin{pmatrix}
\left.\begin{matrix}
3 & 2 & 1\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c+a-2b
\end{matrix}
\end{pmatrix}$$

$rankA = 2$, для выполнения условия несовместимости необходимо, что бы $rankà > 2$, а это возможно при $c+a-2b\neq0$

# Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Найдем определитель матрицы коэффициентов

$$detA=\begin{vmatrix}1 & -2\\
3 & -4\end{vmatrix}=1\cdot -4-(-2)\cdot 3=2\neq 0$$


Система определена и имеет единственное решение


Найдем определители $detA_{1}$, $detA_{2}$

$$detA_1=\begin{vmatrix}1 & -2\\
7 & -4\end{vmatrix}=-4+14=10\\
detA_2=\begin{vmatrix}1 & 1\\
3 & 7\end{vmatrix}=7-3=4$$

Откуда

$$x_1=\frac{detA_1}{detA}=\frac{10}{2}=5\\
x_2=\frac{detA_2}{detA}=\frac{4}{2}=2$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Найдем определитель матрицы коэффициентов

$$detA=\begin{vmatrix}2 & -1 & 5\\
1 & 1 & -3\\
2 & 4 & 1\end{vmatrix} = 2 \cdot \begin{vmatrix}1 & -3\\
4 & 1\end{vmatrix} + 1 \cdot \begin{vmatrix}1 & -3\\
2 & 1\end{vmatrix} + 5 \cdot \begin{vmatrix}1 & 1\\
2 & 4\end{vmatrix} = 2 \cdot 13 + 1 \cdot 7 + 5 \cdot 2 = 43 \neq 0$$

Система определена и имеет единственное решение

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$

$$detA_{1} = \begin{vmatrix}10 & -1 & 5\\
-2 & 1 & -3\\
1 & 4 & 1\end{vmatrix} = 86$$

$$detA_{2} = \begin{vmatrix}2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1\end{vmatrix} = -43$$

$$detA_3=\begin{vmatrix}2 & -1 & 10\\
1 & 1 & -2\\
2 & 4 & 1\end{vmatrix} = 43$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & 0 & 1
\end{pmatrix}$$

Вычтем из второй и третьей строк матрицы $U$ первую строку, умноженную на 2 и 3 соответственно.
В матрицу $L$ добавим эти множители в первый столбец на 2-ю и третью позиции.

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 0 & 1
\end{pmatrix}$$

Вычтем из третьей строки матрицы $U$ вторую строку, умноженную 4.
В матрицу $L$ добавим этот множитель во второй столбец на третью позицию.

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

In [2]:
U=np.array([[1,2,4],[0,5,4],[0,0,2]])
L=np.array([[1,0,0],[2,1,0],[3,4,1]])
print(f'LU = {L@U}')

LU = [[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


Получили исходную матрицу, все верно

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}$$

Из второй, третьей и четвёртой строк вычитаем первую, умноженную на 2, 3 и 4, соответственно

$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 0 & 1 & 0\\
4 & 0 & 0 & 1
\end{pmatrix}$$

Из третьей и четвёртой строк вычитаем вторую, умноженную на 5 и 6, соответственно

$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 0 & 1
\end{pmatrix}$$

Из четвёртой строки вычтем третью, умноженную на 7

$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

Проверим

In [3]:
L=np.array([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]])
U=np.array([[1,1,2,4],[0,3,4,1],[0,0,3,1],[0,0,0,4]])
print(f'LU = {L@U}')

LU = [[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


Получили исходную матрицу, все верно

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [4]:
A=np.array([[2,1,3],[11,7,5],[9,8,4]])
b=np.array([1,-6,-5])
A

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

In [5]:
b

array([ 1, -6, -5])

Найдем матрицы $L$ и $U$

In [8]:
p,L,U=scipy.linalg.lu(A)
print(f'Матрица p: \n{p}\nМатрица L:\n{L}\nМатрица U:\n{U}')

Матрица p: 
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Матрица L:
[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
Матрица U:
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


Решим систему $Ly =b$

In [9]:
def y_search(L,b,p):
    y_arr=np.array([0 for i in range(len(b))],dtype=float)
    b_copy=(p.T@b).astype(np.float)
    for i in range(len(b)):
        for j in range(len(b)):
            tot=(L[i][j]*y_arr[j])
            b_copy[i]-=tot
        y_arr[i]=b_copy[i]/L[i][i]
    return y_arr.reshape(len(b),-1)

y_arr=y_search(L,b,p)
y_arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-6.        ],
       [-0.09090909],
       [ 2.08      ]])

Решим систему $Ux = b$

In [12]:
def x_search(U,y_arr):
    x_arr=np.array([0 for i in range(len(y_arr))],dtype=float)
    b_copy=y_arr.copy()
    for i in range(len(y_arr)-1,-1,-1):
        for j in range(len(y_arr)-1,-1,-1):
            tot=(U[i][j]*x_arr[j])
            b_copy[i]-=tot
        x_arr[i]=b_copy[i]/U[i][i]
    return x_arr.reshape(len(x_arr),-1)

x_arr=x_search(U,y_arr)
x_arr

array([[-1.],
       [ 0.],
       [ 1.]])

$x_1 = -1, x_2 = 0, x_3 = 1$

Проверим

\begin{cases}
2\cdot -1+0+3\cdot 1=1 \\
11\cdot -1+7\cdot 0+5\cdot 1=-6 \\
9\cdot -1+8\cdot 0+4\cdot 1=-5
\end{cases}

Верно

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly = b$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-33,$$

$$y_{3}=\frac{193-295+66}{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=-5,$$

$$x_{1}=\frac{59-25+20}{9}=6.$$

Осуществим проверку, подставив полученные значения в исходную систему:

$$\begin{cases}
81 \cdot 6 -45 \cdot(-5)+45 \cdot (-4)=531 \\
-45 \cdot 6+50 \cdot (-5)-15 \cdot (-4)=-460 \\
45 \cdot 6-15 \cdot (-5)+38 \cdot (-4)=193
\end{cases}$$

Верно!